version: '2'

services:
  jekyll:
    image: jekyll/jekyll
    volumes:
      - ./:/usr/src/app
      - gems:/usr/local/bundle
    working_dir: /usr/src/app
    command: sh -c 'jekyll serve -s /usr/src/app --watch'
    ports:
      - 4000:4000
volumes:
  gems:
    driver: local